# -*- coding: utf-8 -*-
"""Programming Trials

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGvZN4ZqSDkpM7r1dLhxUjBc94H8vFRr
"""

"""
Word Printer Utility
A simple command-line tool that:
- Asks for a word (1-13 chars)
- Asks for print count (1-10, with 3 attempts)
- Asks for case style (upper/lower/title)
- Prints the formatted word the requested number of times

Demonstrates: input validation, loops, functions, error handling, string methods.
No external libraries required.
"""

def get_valid_number(max_attempts=3, max_value=10):
    attempts = 0
    while attempts < max_attempts:
        try:
            number = int(input("How many times to print? "))
            if number <= max_value and number > 0:
                return number
            print(f"Must be from 1 to {max_value}.")
        except ValueError:
            print("Please enter a number.")
        attempts += 1
    return None

def get_valid_word(max_word_length=13):
    while True:
      word = input("What word do you want to print? ")
      if len(word) > max_word_length or len(word)< 1:
       print(f"The word must be 1 to {max_word_length} characters. Please try again.")
      else:
        break
    return word

def print_word(number, word):
  for i in range(number):
        print(word)

def get_style():
    while True:
        style = input("Print in (upper/lower/title)? ").lower()
        if style in ("upper", "lower", "title"):
            return style
        print("Choose: upper, lower, or title")

def format_word(word, style):
    if style == "upper":
        return word.upper()
    elif style == "lower":
        return word.lower()
    elif style == "title":
        return word.title()

def main():
  word = get_valid_word()
  style = get_style()
  word = format_word(word, style)
  number = get_valid_number()

  if number is None:
    print("Too many attempts! Program will end.")
  else:
    print_word(number, word)

if __name__=="__main__":
  main()